combine_control_expr = false
comment_width = 100
control_brace_style = "AlwaysSameLine"
edition = "2021"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = false
imports_layout = "HorizontalVertical"
max_width = 80
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
single_line_if_else_max_width = 0
tab_spaces = 2
trailing_comma = "Vertical"
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true